const PHRASES: readonly string[] = [
  "It works on my machine. Ship the machine.",
  "undefined is not a function. My undefined is a lifestyle.",
  "The best code is the code you delete.",
  "It's not a bug, it's an undocumented feature.",
  "A code review is just someone else judging your midnight decisions.",
  "Git blame exists so you can congratulate yourself six months later.",
  "Documentation is a love letter to your future self. You never write it.",
  "99 little bugs in the code. Take one down, patch it around. 127 bugs in the code.",
  "Real programmers count from zero. So this is actually phrase number zero.",
  "The first rule of optimization: don't. The second: don't yet.",
  "Any fool can write code a computer understands. Few can write code humans do.",
  "Legacy code is just code without tests written by someone who has since left.",
  "Premature optimization is the root of all evil. So is premature abstraction.",
  "A senior dev is just someone who has been bitten by more edge cases.",
  "You don't understand recursion until you understand recursion.",
  "Tabs vs spaces killed a friendship and you know which side you're on.",
  "The cloud is just someone else's computer that you blame when it breaks.",
  "Type safety is not just a compiler feature, it's a lifestyle choice.",
  "If it compiles, ship it. I'm kidding. Run the tests. Or don't. Ship it anyway.",
  "The most dangerous phrase in software: we've always done it this way.",
  "There are only two hard things in CS: cache invalidation, naming, and off-by-one errors.",
  "Stack overflow: where developers go to feel simultaneously smart and stupid.",
  "A PR with no comments means either your code is perfect or nobody read it.",
  "The best error message is the one you spend two hours Googling at 2am.",
  "Merge conflict: two developers who didn't talk to each other, exposed.",
  "Docker: because it worked in the container on my laptop counts as production-ready.",
  "Microservices: turning a monolith problem into a distributed systems problem.",
  "You can't fix what you can't measure. You also can't measure what you won't instrument.",
  "YAGNI until you desperately need it, then you YAGNI'd too hard.",
  "A good commit message is worth a thousand lines of comments.",
  "The junior dev asks how. The senior dev asks why. The principal dev asks if.",
  "Refactoring: changing all the code while claiming nothing fundamentally changed.",
  "Technical debt: the mortgage on your architecture. You're always paying interest.",
  "Rubber duck debugging proves the problem was in your explanation, not the code.",
  "async/await: making asynchronous code look synchronous until the callback hell returns.",
  "The test suite is green. The users are screaming. Both things are true.",
  "Your abstraction is leaking. It was always leaking. You just noticed.",
  "Environment variables: the config you didn't want to commit and then forgot about.",
  "Serverless: still servers. Still cold starts. Still your problem.",
  "Every regex is write-only. Including the one you wrote five minutes ago.",
  "The database is not a message queue. The database should not be a message queue.",
  "Eventual consistency: everything is fine, eventually.",
  "Deploy on Friday. I dare you.",
  "The null pointer is the billion dollar mistake. TypeScript is the billion dollar apology.",
  "You can't have both fast, correct, and cheap. Pick two. You'll pick none.",
  "Continuous integration: the art of breaking things on someone else's machine first.",
  "An API without versioning is a promise you will break with grace.",
  "The code is the documentation. The documentation lies. Trust the code.",
  "Ten minute build time means ten minutes of pretending to be productive.",
  "The best architecture is the one your team can actually understand on Monday morning.",
  "Ship it and see. This is always the plan. Just admit it.",
];

export const FallbackPhraseStore = {
  getRandom(): string {
    const index = Math.floor(Math.random() * PHRASES.length);
    return PHRASES[index] ?? PHRASES[0] ?? "Keep coding.";
  },

  getAll(): readonly string[] {
    return PHRASES;
  },
};
